"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](kurisu_light)\
$os\
$username\
[](bg:kurisu_red fg:kurisu_white)\
$directory\
[](fg:kurisu_red bg:kurisu_light)\
$git_branch\
$git_status\
[](fg:kurisu_accent bg:kurisu_white)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:kurisu_white bg:kurisu_blue)\
$docker_context\
[](fg:kurisu_blue bg:kurisu_dark_red)\
$time\
[ ](fg:kurisu_dark_red)\
$line_break$character"""

palette = 'kurisu_theme'

[palettes.kurisu_theme]
kurisu_dark = "#2a2230"     # Dark background
kurisu_light = "#f9f2f4"    # Light text
kurisu_red = "#954535"      # Kurisu's hair color
kurisu_dark_red = "#6D2F28" # Darker version of her hair
kurisu_accent = "#AD6154"   # Lighter accent of her hair
kurisu_white = "#e9e2e4"    # Lab coat white
kurisu_blue = "#485A8A"     # Blue accent from her outfit
kurisu_gold = "#D1A33D"

[os]
disabled = false
style = "bg:kurisu_dark fg:kurisu_light"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:kurisu_dark fg:kurisu_light"
style_root = "bg:kurisu_dark fg:kurisu_red"
format = '[ $user ]($style)'

[directory]
style = "fg:kurisu_light bg:kurisu_red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol $branch ](fg:kurisu_light bg:kurisu_accent)]($style)'

[git_status]
style = "bg:kurisu_white"
format = '[[($all_status$ahead_behind )](fg:kurisu_light bg:kurisu_accent)]($style)'

[nodejs]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[c]
symbol = " "
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[rust]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[golang]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[php]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[java]
symbol = " "
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[kotlin]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[haskell]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[python]
symbol = ""
style = "bg:kurisu_white"
format = '[[ $symbol( $version) ](fg:kurisu_dark bg:kurisu_white)]($style)'

[docker_context]
symbol = ""
style = "bg:kurisu_light"
format = '[[ $symbol( $context) ](fg:kurisu_dark bg:kurisu_blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:kurisu_dark_red"
format = '[[  $time ](fg:kurisu_light bg:kurisu_dark_red)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:kurisu_red)'
error_symbol = '[](bold fg:kurisu_red)'
vimcmd_symbol = '[](bold fg:kurisu_accent)'
vimcmd_replace_one_symbol = '[](bold fg:kurisu_blue)'
vimcmd_replace_symbol = '[](bold fg:kurisu_blue)'
vimcmd_visual_symbol = '[](bold fg:kurisu_gold)'
